### ISSUE TITLE
Making a suggestion to an initiative

### ISSUE THREAD

**Issue by oliverbarnes** [oliverbarnes/old-participate-client#14]
On an existing initiative, clicking on a link to 'Make a suggestion' opens up a text area to be submitted. The suggestion gets associated with the initiative. 

Like comments on a blog post.

**Comment by oliverbarnes** [comment]
No user will be associated with the suggestion on this iteration.

**Comment by KatiRG** [comment]
Is it better to have suggestions as attributes appended to the initiative model as they come in, or have a separate suggestion model that can be associated to the initiative with belongs_to/has_many?
