### ISSUE TITLE
Posting an initiative to an existing issue

### ISSUE THREAD

**Issue by oliverbarnes** [oliverbarnes/old-participate-client#24]
Once an initiative is posted with a new issue, this issue is open for alternative initiatives.

When viewing an issue, clicking 'Add another initiative' takes you to the initiative form, pre-populated with the issue title.

**Comment by Qianfinland** [comment]
does the viewing an issue feature must work before i implementing this feature?

**Comment by oliverbarnes** [comment]
yes.

**Comment by Qianfinland** [comment]
Do you think we should make initiatives under issues, so url could be issues/1/initiatives/1/suggestions? Currently they are parallel

**Comment by Qianfinland** [comment]
Also if just look the list of issues and initiatives but not look models, a little confused on which initiative belongs to which issue. Need some discussion about this

**Comment by oliverbarnes** [comment]
Hmm, I think it makes sense to keep the parallel top-level initiatives route, and create a new `issues/1/initiatives/new`. About the second question, not sure I understood? Do you mean that, when a user looks at the issues or initiatives listings, it's not clear what they're associated too? If so, that's something we should definitely look into, UX wise. but maybe a separate issue here on github

**Comment by Qianfinland** [comment]
For the second question, yes you guess right. Currently i am implementing "viewing an initiative" feature.

**Comment by Qianfinland** [comment]
what do you mean by "be them alternative or just parallel", what should i deal with this?

**Comment by oliverbarnes** [comment]
I mean they can be in direct opposition to an existing initiative, or just a different, non-related initiative. But come to think of it, they're all alternative :) Doesn't matter, really. Removing it from the description

**Comment by KatiRG** [comment]
PR title changed
