### ISSUE TITLE
Viewing an issue

### ISSUE THREAD

**Issue by oliverbarnes** [oliverbarnes/old-participate-client#25]
As we discuss it over on Slack, it's becoming clear it can be done in different ways, different scenarios:
- while looking at the list of issues, clicking in one of them to expand and view the description.
- visiting the url (or clicking on an link with that url) for an issue, and that render the issues list and scrolls to the issue, highlighting and expanding it (edited)

We probably will have other ones come up. looking at an issue from an initiative, for instance. we can all add the new scenarios to the github issues as we discover them.

The first scenario above, "looking at the list of issues, clicking in one of them to expand and view the description" seems the best one to focus on now. it's simpler and a natural extension to browsing the list of issues

As discussed with @miika yesterday night, it can be done in a emberish way by using a specific route for the issue, within the list. this would involve changing the url (transitioning to the specific route), and that makes sense from a UX perspective as well. Highlighting it visually might make sense as well, as an extra feedback to the user..

This is the reference I sent @miika last night (see last tip "Toggling properties"): http://say26.com/five-useful-tips-for-ember-js-developers

Some code to illustrate what I'm thinking (not tested, and doesn't include the highlight logic):

``` javascript
//router.js
Router.map(function() {
  this.resource('issues', function() {
    this.resource('issue', { path: ':issue_id' })
  });
});

//routes/issue.js
var issueRoute = Ember.Route.extend({
  showDescription: false
});

//templates/issue.emblem
.issue click="toggleProperty 'showDescription'" 
  .title Global warming
  .description visible="showDescription"
    p The end of the world
```

More about binding actions in emblem at the "Action / Events Shorthand" of the syntax docs: http://emblemjs.com/syntax/

**Comment by KatiRG** [comment]
Do you mean make the issues displayed on the list of issues page (/issues) clickable so that the full issue description will be displayed on /issues/:issue_id?

**Comment by oliverbarnes** [comment]
Yes, and here’s a challenge for you - making this happen within the listing, an expansion of the issue. I don’t expect issue descriptions to be too big for that

Oliver

**Comment by KatiRG** [comment]
You mean like having a "read more" link that expands the text?

**Comment by oliverbarnes** [comment]
Yes, but you can make the whole thing be clickable. The whole li

Oliver

**Comment by KatiRG** [comment]
OK, so this means that the issue does NOT open in /issues/:issue_id when it is clicked on, but displays on the same /issues page, correct?

**Comment by oliverbarnes** [comment]
You can have the url transition to /issues/:issue_id and still display on the same page, that’s one of the things ember is good at. You can even then link to that, and when loading it’ll show the issue within the listing.

Like this:

http://discuss.emberjs.com/t/best-way-to-handle-loading-thousands-of-records/6087/5

you can check the discourse codebase itself to see how they implement it.

(extra cookie points if you can implement that color effect as well ;)

Oliver

**Comment by KatiRG** [comment]
This link seems to discuss pagination of a large number of records. I don't see how it is about displaying a record on the same page when the url goes to another page.

**Comment by KatiRG** [comment]
can you send a link from discourse.org that shows what you mean? i have only found that discussions open up into new pages.

**Comment by oliverbarnes** [comment]
The link I sent isn't meant for the content, but for the interface behavior in Discourse - notice how it's a link to the specific comment within a list of comments in a discussion, and how there's a color effect after the page loads, to further establish the comment that's being linked?

**Comment by KatiRG** [comment]
I'm guessing renderTemplate? http://emberjs.com/guides/routing/rendering-a-template/

**Comment by KatiRG** [comment]
I must be missing something, because http://discuss.emberjs.com/t/best-way-to-handle-loading-thousands-of-records/6087/2 is not a discourse discussion.

**Comment by oliverbarnes** [comment]
I'm not explaining this well =D It's friday, end of day, no brains left

So, the Discuss Emberjs forum uses Discourse as its engine. This specific thread I sent you the link for, which has nothing to do with what we're, well, discussing, is an example of using ember to list resources, and have a route to single resource in it (a comment).

In other words, forget the content of the discussion there, just focus on the UX. It's ember rendering a list of resources (comments), and then a specific resource within it (a comment).

The link to the full comments list is: 

http://discuss.emberjs.com/t/best-way-to-handle-loading-thousands-of-records/6087

The link to the specific embedded comment is:

http://discuss.emberjs.com/t/best-way-to-handle-loading-thousands-of-records/6087/5

Here's another comment in that list:

http://discuss.emberjs.com/t/best-way-to-handle-loading-thousands-of-records/6087/9

**Comment by Qianfinland** [comment]
This feature makes me wonder : do we also need viewing an initiative feature?

**Comment by oliverbarnes** [comment]
Good point, would you add it to the list of features to be done, please?

Oliver

**Comment by KatiRG** [comment]
is this relevant? "Previously, a 'toggleProperty' action would invoke the controller's toggleProperty method. Now, the behavior is the same but with a deprecation warning. To eliminate the deprecation warning, define 'toggleProperty' on the controllers actions hash and call this.toggleProperty(...)"

https://github.com/emberjs/ember.js/issues/3296

**Comment by oliverbarnes** [comment]
Hmm, I think it's good to know at least. But if the deprecation warning gets too annoying, feel free to declare it explicitly in the controller. Might need to do that at some point anyway, to get the highlight effect
