### ISSUE TITLE
Listing suggestions

### ISSUE THREAD

**Issue by KatiRG** [oliverbarnes/old-participate-client#30]

**Comment by KatiRG** [comment]
@oliverbarnes Where should the link to the List of Suggestions go? On the /initiatives page beside each initiative list item? or on the /initiatives/:initiative_id page, somewhere under Support this initiative or Make a suggestion?

**Comment by oliverbarnes** [comment]
Hey, on the /initiatives/:initiative_id (initiative details) view, thanks

**Comment by KatiRG** [comment]
If there are no suggestions associated with an initiative, should a message be displayed, or is that a separate feature to do? Right now, the user gets an empty list with title "Suggestions:"

**Comment by oliverbarnes** [comment]
yes, maybe just change the 'Suggestions' header to 'No suggestions made to this initiative yet. Be the first!" or something like it?
