### ISSUE TITLE
Test bug: Assertion Failed: calling set on destroyed object

### ISSUE THREAD

**Issue by oliverbarnes** [oliverbarnes/old-participate-client#34]
Test that previously ran fine barfs with this

```
ok 5 PhantomJS 1.9 - Supporting an initiative Successfully
not ok 6 PhantomJS 1.9 - Supporting an initiative "after each" hook
    ---
        message: >
            Assertion Failed: calling set on destroyed object
        stack: >
            Error: Assertion Failed: calling set on destroyed object
```

Seems like an async side effect from another test

**Comment by Qianfinland** [comment]
Yesterday i got the same error when writing test for support validation, once the visit code is written, then the error occurs

**Comment by oliverbarnes** [comment]
yeah, it's weird. fun with async tests... might also be just our setup with mocha adapter that's buggy. a possibility would be to switch to [qunit-bdd](https://github.com/square/qunit-bdd)

**Comment by KatiRG** [comment]
To get `ember test` to run for the 'listing initiatives' feature (#26), two tests have to be commented out: making-a-suggestion-to-initiative-test and 'supporting-an-initiative-test'

**Comment by Qianfinland** [comment]
also within one test file, one part of test code could break the part of test code, i comment in the support validation branch under supporting-an-initiative-test.js

**Comment by Qianfinland** [comment]
Piotr from the help desk checks our code, he says "it seems that this is because the cleanup is somehow broken between the tests - so, models from a previous tests are destroyed, but something tries to still use them"

**Comment by Qianfinland** [comment]
Piotr: it might be actually a bug in Ember Data code, essentially the error is this: you call App.destroy(), which among the other things also removes all records from the store and for some reason it fails

**Comment by oliverbarnes** [comment]
Not sure, my impression is it's a conflict between tests that are running in parallel, waiting for promises to be finished asynchronously.

So test1 starts the app, and starts going through the test steps,

Then test2 starts the app, and does the same.

When test1 ends, it destroys the App instance. But it destroys it globally

When test2 tries to cleanup (or perhaps even before that, when saving stuff), doesn't find App, and barfs.

Make sense?

**Comment by drogus** [comment]
@oliverbarnes the problem occurs in `unloadAll` method called on a store. Among the other things it calls `clearRelationships()` on records, which may set a `belongsTo` property to null (like `record.set('issue', null)`. If the record is destroyed, it will fail. Here is a backtrace:

![](http://drogus-s3itch.s3.amazonaws.com/rgsoc-specs-backtrace-20140819-193422.png)

**Comment by oliverbarnes** [comment]
Thanks @drogus, but isn't it what we should expect from a test teardown? The problem seems to be it's also clearing the state for other tests, unless I'm missing something. Do you have any suggestions?

**Comment by drogus** [comment]
@oliverbarnes sorry, I should have elaborated a bit more. My comment wasn't in any way trying to contradict what you wrote above, I just wanted to add a bit more details on where the problem occurs.

> The problem seems to be it's also clearing the state for other tests, unless I'm missing something.

Yup, given 2 exactly the same tests, it will fail only on the second run (or at least I wasn't able to reproduce in any other configuration). Given that the entire `App` object is destroyed, it's extremely weird for me, but I'll maybe try to dig into it later or tomorrow.

**Comment by oliverbarnes** [comment]
@drogus all good, and it's fine to contradict too :) just trying to flesh out the problem myself. yeah, that's what I get too, the individual tests pass, but break one another when destroying App on teardown. It really might just be our setup is precarious with the mocha-adapter hack. Perhaps qunit-bdd might be worth a try, and would also give us the describe() syntax... Have you used it at all?

**Comment by drogus** [comment]
@oliverbarnes I figured out the problem. It seems that when fixture adapter loads the records it uses the objects returned from `Model.FIXTURES` and directly feeds them to the store. Because of that, when store changes the attributes it actually changes it on global `FIXTURES` object and for example `issue: 1` becomes `issue: actualIssueObject`. A fix is to clone `FIXTURES` before using them. I can submit a proper patch to ember data tomorrow, but for now the app can be fixed by changing `app/adapters/application.js` to:

``` javascript
export default DS.FixtureAdapter.extend({
  fixturesForType: function(type) {
    var result = this._super(type);
    if(result) {
      result = Ember.EnumerableUtils.map(result, function(fixture) {
        return jQuery.extend({}, fixture);
      });
    }
    return result;
  }
});
```

**Comment by oliverbarnes** [comment]
Ok, you're hired @drogus :) applied your change and it's up on master. thanks a bunch! also liking your post about rails arch, good read

**Comment by drogus** [comment]
One correction, it needs to be a deep clone, so the code should be:

``` javascript
export default DS.FixtureAdapter.extend({
  fixturesForType: function(type) {
    var result = this._super(type);
    if(result) {
      result = Ember.EnumerableUtils.map(result, function(fixture) {
        return jQuery.extend(true, {}, fixture);
      });
    }
    return result;
  }
});
```

(notice `true` as a first argument of `jQuery.extend`)

**Comment by oliverbarnes** [comment]
ok so `return jQuery.extend(true, {}, fixture)`?

**Comment by drogus** [comment]
@oliverbarnes yup, while I was checking other thing I noticed that if you run the "Making a suggestion to an initiative" test twice, the initiative will have more and more suggestions

**Comment by oliverbarnes** [comment]
thanks, yeah we ran into that too, and so far just winging it by picking the first selector result. why do you figure? first App.destroy() does too much, then falls short...

**Comment by drogus** [comment]
> thanks, yeah we ran into that too, and so far just winging it by picking the first selector result. why do you figure? 

I think that I have a confusing way of expressing myself today :) What I meant in my previous comment is that making a deep clone (that is `extend(true, {}, fixture)`) is a fix for the problem of accumulating suggestions. The source of this bug is similar to the first one - array of suggestions from a fixture object is used throughout all tests. Deep clone fixes it by always using a different array object.

**Comment by oliverbarnes** [comment]
oohh, I see! makes sense now. thanks again, and don't worry as the fix more than makes up for the confusion ;)
