### ISSUE TITLE
Registration and authentication

### ISSUE THREAD

**Issue by oliverbarnes** [oliverbarnes/old-participate-client#4]
Simple and oAuth (Facebook, Twitter)

**Comment by Qianfinland** [comment]
should we use this library https://github.com/simplabs/ember-simple-auth

**Comment by oliverbarnes** [comment]
I haven't looked into the different options yet. Any good tutes about it? Would be nice to see other options as well

**Comment by oliverbarnes** [comment]
Just went through their README and it seems like a pretty awesome lib

**Comment by oliverbarnes** [comment]
WIP using ember-simple-auth on the [sign-up branch](https://github.com/oliverbarnes/participate/tree/sign-up)
