### ISSUE TITLE
viewing an initiative 

### ISSUE THREAD

**Issue by Qianfinland** [oliverbarnes/old-participate-client#46]
Similar as issue 25: viewing an issue , here is the link https://github.com/oliverbarnes/participate-frontend/issues/25

**Comment by Qianfinland** [comment]
is there some difference between this feature and viewing an issue?

**Comment by Qianfinland** [comment]
Just to be sure on what i need to do. There is a list of initiatives titles(for example title1, title 2 and title 3), i want to click one title, for example title 1, then it expands description about title 1. Other titles don't expands until i respectively click them then they expand their descriptions. In addition, when i click each title, page doesn't change. Please correct me if i am wrong

**Comment by oliverbarnes** [comment]
Qian, they're different actually, something I discussed with Cathy before - I expect initiatives to have much bigger bodies of text than issues, so expanding them completely within the listing might not be helpful. Also, initiatives have issue information as well, as part of it.

Expanding partially (a small preview) could be useful, but viewing the complete initiative, on its own, would be a higher priority.

So clicking on the initiative title (the whole li element would be good, so the whole row is clickable) would replace the listing with the initiative. The initiative view should include title, description, and the issue - here I'm not sure how the issue should show up. Maybe an expandable title as well, so its description doesn't compete with the initiative's own description?

**Comment by Qianfinland** [comment]
Talking about expanding partially, do i need to do this? When i click initiative title 1, initiative description shows partially and with "see more"  link. Not that clear about what kind content will display after click "see more" . Just whole description of title 1 and page stays the same?   Or content include title, description and issue  and page url changes?

**Comment by oliverbarnes** [comment]
no, I meant that you don't need to do this. Viewing the initiative on its own (not within the list), which is the primary view for it, is the essential thing

**Comment by Qianfinland** [comment]
you mean i don't need to do the "Viewing an initiative" ?

**Comment by oliverbarnes** [comment]
I mean doing "Viewing an initiative" differently from viewing issues: instead of expanding the initiative within a list of initiatives, transitioning to another "page", by itself. Outside the list

("page" in quotes because it's really all a single-page application)

**Comment by Qianfinland** [comment]
click the title and then it will transition to another page, no need to do partial expanding? could you give example of webpage that has similar feature?

**Comment by oliverbarnes** [comment]
it's the normal link behavior - click on it, show the page. nothing special, it's the expansion idea from issues that's confusing the whole thing :) I need to start wireframing / story boarding now that we're getting into more UX stuff

**Comment by KatiRG** [comment]
@Qianfinland we have done this already. See "Display a clickable list that
opens onto a new page" in our RGSoC document if you need to...
