### ISSUE TITLE
bug remove support

### ISSUE THREAD

**Issue by Qianfinland** [oliverbarnes/old-participate-client#49]
Cathy found a bug on making a suggestion, when click "Support this initiative" then click "Make a suggestion", box and submit button show. BUT without clicking submit button(you can leave it empty or just type something in box), if you click "Remove support for this initiative", the box and submit button will show together with "Support this initiative". Normally box and button shouldn't show. In addition, if you click the "Support this initiative", the box and submit button will also show.

Also, after you submit suggestion and click"Remove support for this initiative", your suggestions will be shown together with "Support this initiative". If you remove support, suggestions normally shouldn't be shown.

**Comment by Qianfinland** [comment]
i fix this problem by just adding line code in routes/initiative.js inside removeSupport
this.transitionTo('initiative');

**Comment by Qianfinland** [comment]
In terms of user behavior on removing support, currently 3 cases as below: 
1. they may remove support before they make suggestion(not  yet clicking "Make a suggestion")
2. or during(already click "Make a suggestion" but not yet click submit button) 
3. or after already submitting suggestions. 
Wonder do i need to write test for "removing support during or after submitting suggestions", before we have done "remove support before making a suggestion" in the supporting-an-initiative-test.js

**Comment by oliverbarnes** [comment]
Nice catch, and good thinking with the scenarios. Yes, a test "Removing support", with the different scenarios, would be great. Also: whenever finding a bug or a new feature/scenario like now, the first step should to write the test for it, before implementing a fix or the new feature/scenario.

It's good even to submit a pull request describing a bug with a breaking test by the way, so that, if you're working on something else, somebody else can look at it. Thanks @Qianfinland

**Comment by Qianfinland** [comment]
Cathy found the bug, i only fix it, thanks Cathy also :)

**Comment by oliverbarnes** [comment]
thanks @KatiRG :)

**Comment by Qianfinland** [comment]
now i find another bug, when manually type url /initiatives/1/suggestions/new, it shows "Support this initiaitve" AND together with the make suggestion box and submit button. We not yet support, so shouldn't be able to make suggestion.

**Comment by oliverbarnes** [comment]
Add a breaking test that describes it (see my other comment above)

**Comment by Qianfinland** [comment]
Now again about user behavior on making suggestions, currently 2 types
1. at url /initiatives/1, then on that page click "Support this initiaitve" , then click "Make a suggestion" as we assumed before
2. by manually type url /initiatives/1/suggestions/new, this url is not controlled by clicking behavior as it always exists when we define the route. I don't know how to deal with this type, currently. Tried add isSupported in the suggestions/new.emblem, not work yet. Any suggestions on the manually typing url?

**Comment by oliverbarnes** [comment]
isSupported is a property of the initiative controller, under /initiatives/1/suggestions/new the default controller will be related to SuggestionsNewRoute. I think you might need to set another property, on this controller so it's visible to the template.

Please add the tests I mentioned above, and let's continue this over a pull request?

**Comment by Qianfinland** [comment]
i will add the tests soon, after finishing the process of rebasing :)

**Comment by oliverbarnes** [comment]
yes, but what I mean is adding the tests before trying for a fix... seems like you're trying fixes first

**Comment by Qianfinland** [comment]
after you told me to add breaking test then stop fixing
