### ISSUE TITLE
Delete suggestions on support removal

### ISSUE THREAD

**Issue by Qianfinland** [oliverbarnes/old-participate-client#56]
when users click "Remove support for this initiative", suggestion posted by users before are also will be removed

**Comment by Qianfinland** [comment]
i wonder could delete suggestion in othere way, each suggestion has a delete button? Also wonder, should we also have a edit button for each suggestion, so user can refine or re-edit their suggestion ?

**Comment by oliverbarnes** [comment]
definitely, I've renamed this feature to differentiate from the itemized removal. Editing would be another separate feature
