### ISSUE TITLE
bug on manually typing url

### ISSUE THREAD

**Issue by Qianfinland** [oliverbarnes/old-participate-client#58]
when manually typing /initiatives/1/suggestions/new, it shows "support this initiatiative" together with the suggestion box and aubmit button. Users cannot make suggestion before they support initiatiave

**Comment by oliverbarnes** [comment]
thanks Qian, now please submit a pull request with a breaking test demonstrating the bug?

As for the solution, could be a simple check for the initiative isSupported flag, if it's false transition to /initiatives/1

**Comment by Qianfinland** [comment]
i make the PR, i try another way to fix the bug, move the outlet below = link-to 'suggestions.new'  | Make a suggestion. Still have partially problem, suggestion box and button doen't show before click "Support thid initiative". But after click support, the suggestion box and button appear, users can make suggestion without click "Make a suggestion". I will try your method when at home, now need to run to catch tram :)
