### ISSUE TITLE
Areas

### ISSUE THREAD

**Issue by oliverbarnes** [oliverbarnes/old-participate-client#62]
Epic to be broken down into smaller user stories and tasks later.

Issues belong to areas like 'Housing', 'Healthcare', 'Transport/Mobility', 'Environment', etc.

When an issue is created, an area will have to be selected.

Once we have users on the system and vote delegation, users will be able to delegate to another based on area

**Comment by KatiRG** [comment]
what is epic?

**Comment by KatiRG** [comment]
Should there be an explicit link to create an issue? eg "Create new issue". If so, should it go in application.emblem along with "Start a new initiative?"

**Comment by oliverbarnes** [comment]
Epic is a big functionality chunk that needs to be broken down into separate user stories:

http://www.mountaingoatsoftware.com/blog/stories-epics-and-themes

The User Stories Applied book has more on it. 

About the create issue link, that would be an interface detail for one of the user stories this gets broken down into (like, say, "Viewing an area").
