### ISSUE TITLE
Delete suggestion

### ISSUE THREAD

**Issue by oliverbarnes** [oliverbarnes/old-participate-client#66]
Itemized deletion of suggestions.

It'd be nice to have the delete link appear when hovering the cursor over the suggestion, so it's not there at all times. Less noisy and helps focus on the content

**Comment by Qianfinland** [comment]
@oliverbarnes there is a small bug on our app now 
---when type url /intitives/1, we have a list of suggestions, 
---when type url/initiatives/1/suggestions we also have list of suggestions, but those suggestions are duplicated as we have suggestions/index.emblem and in the initiative.emblem we also write code to list them. 
--- My code on delete suggestions on /initiatives/1/suggestions works now not the other 
---Do we need to delete the suggestions/index.emblem file?

**Comment by KatiRG** [comment]
@oliverbarnes We discovered that the delete button actually does work for fixture-0 suggestions, the problem is the old suggestion duplication problem: when the user makes a suggestion, TWO copies get created in Ember data (fixture-0 and fixture-1). So when the delete button is clicked, fixture-1 is deleted, but fixture-0 remains.

**Comment by oliverbarnes** [comment]
Thanks, might need to fix the bug first, and then the suggestions deletion.

Please create a separate pull request with a test demonstrating the bug, and only the bug (no deletion code), and let's keep this issue here open for the suggestions deletion feature

**Comment by Qianfinland** [comment]
hi @oliverbarnes, i think we can delete the suggestions/index.emblem file. Now my situation is i can delete the suggestions from the fixture BUT has problem on the newly created suggestions. First click the delete button, it deletes the fixture-1 one, not the fixture-0 one. The reason is Cathy mention above.
What do you want to me to test?

**Comment by oliverbarnes** [comment]
Create a test that replicates what Cathy is describing, the duplication. Then we can discuss and implement a fix there, separate from the deletion feature. About suggestions/index.emblem, would you elaborate? I didn't understand.

**Comment by Qianfinland** [comment]
I don't know how to test duplication of suggestion in the ember-data, as in
the template only shows one.
suggestions/index.emblem is not needed, as in the
tempaltes/initiative.emblem, it has code for listing the suggestions.

**Comment by KatiRG** [comment]
i'm trying to work out a test but have been unsuccessful so far

**Comment by Qianfinland** [comment]
could you give me an example for hovering the cursor then a delete link appears? I see some example on hovering the cursor and text appears, but how could user does the click? as once you moves the cursor, text will disappear, it's impossible to click delete link.

**Comment by oliverbarnes** [comment]
So when you test the steps you described, the duplication doesn't happen @KatiRG?

@Qianfinland Discourse has some hover functionality over their listings. the buttons aren't hidden in their case, but greyed out. When hovering over each item, the buttons get highlighted and are accessible. It's a "discoverable" type of UX

**Comment by KatiRG** [comment]
there is duplication, you can see it with Ember Data when you make a new suggestion. You will see that two copies get made with ids fixture-0 and fixture-1

**Comment by oliverbarnes** [comment]
Yes, but when the test goes through the same steps, does the duplication happen there too? @drogus, would you have some time to help the girls with this?

**Comment by KatiRG** [comment]
@oliverbarnes @drogus I managed to remove the duplication in this PR https://github.com/oliverbarnes/participate-frontend/pull/74
