### ISSUE TITLE
Edit initiative

### ISSUE THREAD

**Issue by oliverbarnes** [oliverbarnes/old-participate-client#69]

**Comment by Qianfinland** [comment]
1. Could you give some description on what kind of situation to edit the initiative? 
2. Is it click one edit button then user can edit all thing like http://jkneb.github.io/ember-crud/#/users/cm6p8 
   Another example on edit button for all http://embersherpa.com/articles/crud-example-app-without-ember-data/app/#/photos 
3. Or is it  each title and description has their own edit button?http://ember-examples-modal.herokuapp.com/#/widgets

**Comment by oliverbarnes** [comment]
Good questions - I like the approach done here on Github. Clicking on 'edit' next to the title opens an in-place form with a save button and cancel link, while hiding the 'edit' button. 

In our case, the simplest might be to use the Github example for editing the title, but instead of just opening an in-place editor for it, opening the whole initiative form (like your option 2). What do you think?
