### ISSUE TITLE
Delegate support for a proposal to another user

### ISSUE THREAD

**Issue by oliverbarnes** [oliverbarnes/old-participate-client#89]
The user flow I see for this 
- viewing a proposal
- opting to delegate support
- selecting another user to delegate to

"Delegate" is a pretty formal word, wish I could find a friendlier/less formal one

eventually, I'd like to see something for quickly delegating support for proposals from the proposals list. On mobile, maybe touching and holding the touch until an option to delegate appears.

**Comment by oliverbarnes** [comment]
on it

**Comment by thedeeno** [comment]
If you're looking for something playful I think "champion" is a good fit. You can use this conceptual space to do lots of cool naming too.

**Comment by oliverbarnes** [comment]
yeah, that's a tough one, like we discussed on slack. My impression is some people might like it, others might be put off by it and not think it's a serious-enough thing... With big variation of meaning depending on the language as well. LiquidFeedback uses `trustee`, which is in the other end of the spectrum and pretty lawyerly... I'd say we wait and see what feedback users give us. And research other synonyms as we go too

**Comment by oliverbarnes** [comment]
quick google for synonyms:

for the noun:
`representative, envoy, emissary, commissioner, agent, deputy, commissary; spokesperson, spokesman, spokeswoman; ambassador, plenipotentiary`

for the verb:
`assign, entrust, pass on, hand on/over, turn over, devolve, depute, transfer`
`authorize, commission, depute, appoint, nominate, mandate, empower, charge, choose, designate, elect`

I like plenipotentiary. 

...kidding.

Spokesperson is a possibility maybe? Maybe we can keep a internal `delegate` term and play with different ones on the interface
