### ISSUE TITLE
Setup Code Climate

### ISSUE THREAD

**Issue by oliverbarnes** [oliverbarnes/old-participate-client#9]
For code quality reports https://codeclimate.com

**Comment by Qianfinland** [comment]
@oliverbarnes  should we also use the code climate?

**Comment by oliverbarnes** [comment]
yes, we'll all use it - it'll be a single account connected to the repo. Here's [Grape's code climate](https://codeclimate.com/github/intridea/grape), so you can see what it'll look like. I'll update here when it's setup and we'll go over it
